"""Add game_user Association Table

Revision ID: 9893baf4782a
Revises: b814edf7a5e3
Create Date: 2023-02-18 10:16:44.914782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9893baf4782a'
down_revision = 'b814edf7a5e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
